#!/bin/sh

install_pdftk_script() {
    fancy_echo "Installing Pdftk ..."
    curl -o ~/Downloads/pdftk_download.pkg https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg

    pkgutil --expand ~/Downloads/pdftk_download.pkg ~/Downloads/pdftk_package

    cd ~ && mkdir /usr/local/Cellar/pdftk /usr/local/Cellar/pdftk/2.02 /usr/local/Cellar/pdftk/2.02/bin /usr/local/Cellar/pdftk/2.02/lib /usr/local/Cellar/pdftk/2.02/share /usr/local/Cellar/pdftk/2.02/share/man /usr/local/Cellar/pdftk/2.02/share/man/man1

    mv ~/Downloads/pdftk_package/pdftk.pkg/Payload ~/Downloads/pdftk_package/pdftk.pkg/payload.gz

    gunzip ~/Downloads/pdftk_package/pdftk.pkg/payload.gz

    cd ~/Downloads/pdftk_package/pdftk.pkg/ && cpio -iv < ~/Downloads/pdftk_package/pdftk.pkg/payload && cd ~

    cd ~ && mv Downloads/pdftk_package/pdftk.pkg/bin/pdftk /usr/local/Cellar/pdftk/2.02/bin/pdftk && mv Downloads/pdftk_package/pdftk.pkg/lib/* /usr/local/Cellar/pdftk/2.02/lib/ && mv Downloads/pdftk_package/pdftk.pkg/man/pdftk.1 /usr/local/Cellar/pdftk/2.02/share/man/man1/pdftk.1

    brew link pdftk
}

append_to_file "$HOME/.gemrc" 'gem: --no-document'

# Spark recommended stuff
brew cask install brave-browser
brew cask install dashlane
brew cask install firefox
brew cask install iterm2
brew cask install postman
brew cask install psequel
brew cask install slack
brew cask install visual-studio-code

fancy_echo "Installing Bundler and setting cores..."
sudo gem install bundler

fancy_echo "Configuring Bundler ..."
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

install_pdftk_script

fancy_echo "Installing itermocil, Oh My Zsh and dotfiles"
brew install TomAnthony/brews/itermocil
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

git clone git@github.com:sprk/spark-tools.git
mv ~/spark-tools/dotfiles ~/.files
append_to_file "$HOME/.files/zshrc/private" 'export AWS_ACCESS_KEY_ID=""'
append_to_file "$HOME/.files/zshrc/private" 'export AWS_SECRET_ACCESS_KEY=""'
append_to_file "$HOME/.files/zshrc/private" 'export SPARK_SEED_ADMIN_EMAIL=""'

ln -nsf ~/.files/itermocil ~/.itermocil
ln -nsf ~/.files/zshrc/.zshrc ~/.zshrc
ln -nsf ~/.files/zshrc/.zshenv ~/.zshenv

fancy_echo "Finished setting up your command line interface"

brew cleanup
brew doctor

# fancy_echo "Ruby Setup"
# TODO - use scripting magic to grab official version from https://github.com/sprk/spark/blob/master/.ruby-version

# fancy_echo "Installing latest ruby"
# rbenv install 2.6.5
# rbenv global 2.6.5
# rbenv rehash
# gem install bundler

# fancy_echo "Installing Spark Ruby"
# rbenv install 2.5.7
# rbenv rehash

# fancy_echo '...Finished Ruby installation checks.'

fancy_echo 'All done!'
